# -*- coding: utf-8 -*-
"""Building An agentic RAG pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19HFe5cM5f7DV6_lKOrV6aSrqdSLeqR4O
"""

#import local file
from google.colab import files
uploaded = files.upload()

#List the file
import os
current_path = os.getcwd()
for x in os.listdir(current_path):
  print(x)

"""### 1. Setup and Dependency Installation

First, we'll install all necessary Python packages. These packages include `langchain`, `langchain-community`, `langchain-chroma`, `transformers`, `sentence-transformers`, and `pypdf`, which are crucial for building our RAG (Retrieval-Augmented Generation) system.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# # Create a requirements.txt file with all necessary libraries
# echo "langchain
# langchain-community
# langchain-chroma
# transformers
# sentence-transformers
# pypdf" > requirements.txt
# 
# # Install packages from requirements.txt
# pip install -r requirements.txt
# 
# # Uninstall and reinstall langchain-chroma and chromadb to ensure compatibility
# # This step resolves potential dependency conflicts and ensures the latest compatible versions.
# pip uninstall -y chromadb langchain-chroma
# pip install langchain-chroma

"""### 2. Import Libraries and Load PDF Documents

We import the required libraries for document loading, text splitting, embeddings, and the RAG framework. Then, we define a function to load PDF documents from a specified folder. In this case, we'll load the `Machine Learning with Python Cookbook (en).pdf` file, which was previously uploaded to the Colab environment.
"""

import os
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from transformers import pipeline
from langchain_chroma import Chroma

# Function to load PDF documents from a specified folder
def load_docs(folder_path):
    docs = []
    for file in os.listdir(folder_path):
        if file.endswith(".pdf"):
            loader = PyPDFLoader(os.path.join(folder_path, file))
            docs.extend(loader.load())
    return docs

# Specify the folder where your PDFs are stored (e.g., '/content' for Colab uploads)
docs = load_docs("/content")
print(f"PDF Pages Loaded: {len(docs)}")

"""### 3. Split Documents into Chunks

To effectively process large documents and retrieve relevant information, we split the loaded PDF pages into smaller, manageable chunks. We use `RecursiveCharacterTextSplitter` to ensure chunks are contextually coherent, with a defined `chunk_size` and `chunk_overlap`.
"""

# Initialize the text splitter with a chunk size of 500 characters and an overlap of 80 characters
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=80
)

# Split the documents into chunks
chunks = text_splitter.split_documents(docs)
print(f"Chunks Created: {len(chunks)}")

"""### 4. Create Embeddings and Vector Database

We convert the text chunks into numerical vector representations (embeddings) using a pre-trained `HuggingFaceEmbeddings` model (`all-MiniLM-L6-v2`). These embeddings are then stored in a `Chroma` vector database, which allows for efficient similarity search to retrieve relevant chunks.
"""

# Initialize the HuggingFace embeddings model
embedding_model = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

# Extract text content from chunks for embedding
texts = [c.page_content for c in chunks]

# Create a Chroma vector database and add the text embeddings
db = Chroma(
    collection_name="rag_store",
    embedding_function=embedding_model
)
db.add_texts(texts)

# Configure the retriever to fetch the top 3 most relevant documents
retriever = db.as_retriever(search_kwargs={"k": 3})
print("Chroma DB and Retriever initialized.")

"""### 5. Load the Local Large Language Model (LLM)

We load a local Large Language Model (`google/flan-t5-base`) using the `transformers` pipeline for text generation. This LLM will be used to generate answers based on the retrieved context.
"""

# Initialize the text generation pipeline with 'google/flan-t5-base' model
llm = pipeline(
    "text-generation",
    model="google/flan-t5-base",
    max_new_tokens=150 # Limit the number of generated tokens
)
print("Local LLM ('google/flan-t5-base') loaded.")

"""### 6. Define Agent Controller

This simple agent controller decides whether to perform a document search (RAG) or answer a query directly based on keywords present in the user's question. This helps in routing questions appropriately.
"""

# Define an agent controller function to decide the action based on the query
def agent_controller(query):
    q = query.lower()
    # If the query contains keywords related to document content, trigger a search
    if any(word in q for word in ["pdf", "document", "data", "summarize", "information", "find", "book"]):
        return "search"
    # Otherwise, answer directly using the LLM without RAG
    return "direct"

print("Agent controller defined.")

"""### 7. Implement the RAG Pipeline

The `rag_answer` function orchestrates the RAG process. It uses the `agent_controller` to determine if a search is needed. If so, it retrieves relevant document chunks from the Chroma DB and constructs a prompt with this context for the LLM. Otherwise, it sends the query directly to the LLM.
"""

# Define the RAG answer generation function
def rag_answer(query):
    # Determine the action (search or direct) using the agent controller
    action = agent_controller(query)

    if action == "search":
        print(f"🕵️ Agent decided to SEARCH document for: '{query}'")
        # Retrieve relevant documents based on the query
        results = retriever.invoke(query)
        # Combine the page content of the retrieved documents into a single context string
        context = "\n".join([r.page_content for r in results])
        # Construct the final prompt for the LLM, including the retrieved context
        final_prompt = f"Use this context:\n{context}\n\nAnswer:\n{query}"
    else:
        print(f"🤖 Agent decided to answer DIRECTLY: '{query}'")
        # If no search is needed, the final prompt is just the original query
        final_prompt = query

    # Generate the response using the loaded LLM
    response = llm(final_prompt)[0]["generated_text"]
    return response

# --- Test the RAG Pipeline ---

print("\n--- Testing RAG Pipeline ---")

# Test 1: A document-specific question (should trigger RAG search)
query_doc_specific = "Give me a 5-point summary from the PDF"
print(f"\nQuery: {query_doc_specific}")
print(f"Response: {rag_answer(query_doc_specific)}")

print("\n" + "-" * 30 + "\n")

# Test 2: A general knowledge question (should trigger direct answer)
query_general = "What is machine learning?"
print(f"Query: {query_general}")
print(f"Response: {rag_answer(query_general)}")

print("\n" + "-" * 30 + "\n")

# Test 3: Another document-specific question
query_another_doc = "What are the main topics discussed in this book?"
print(f"Query: {query_another_doc}")
print(f"Response: {rag_answer(query_another_doc)}")